### ISSUE TITLE
SSH Query Client 

### ISSUE THREAD

**Issue by Xyaren** [Unity-Technologies/go-ts3#31]
TeamSpeak announced that beginning with version 3.14.0 will disable "raw/telnet" server query by default.

> - The next release (3.14.0) will disable raw query (i.e. telnet) as a default query_protocol. It will still be available, but please consider using SSH or HTTP query where possible.
From https://community.teamspeak.com/t/server-3-13-0-beta/12361

Please consider adding support for the SSH query protocol:
- Allow connecting via SSH
- Add host key verification support.

**Comment by stevenh** [comment]
Thanks for the heads up @Xyaren happy to review a PR which adds support for this.
